# Generated by Django 4.2.7 on 2024-11-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='destination',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.CharField(default='Morocco', max_length=200),
        ),
        migrations.AddField(
            model_name='destination',
            name='max_group_size',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='destination',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='destination',
            name='trip_type',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('cultural', 'Cultural'), ('desert', 'Desert Safari'), ('nature', 'Nature'), ('umrah', 'Umrah')], max_length=20),
        ),
    ]
