# Generated by Django 4.2.7 on 2024-12-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_coupon_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reference_number',
            field=models.CharField(default='LEGACY000000', editable=False, max_length=20, unique=True),
        ),
    ]
